# Generated by Django 2.2.11 on 2020-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soal',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('Soal', models.TextField(max_length=500)),
                ('jawab1', models.CharField(max_length=128)),
                ('jawab2', models.CharField(max_length=128)),
                ('jawab3', models.CharField(max_length=128)),
                ('jawab4', models.CharField(max_length=128)),
                ('sbenar', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'soal',
            },
        ),
    ]
